### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by tobwen** [dsci4-hacks/Delete-Teams-Messages-Batch-Bulk-Delete#1]
## bug report
https://github.com/dsci4-hacks/Delete-Teams-Messages-Batch-Bulk-Delete/blob/a68ef14edd355f4b0db62b113133db908c8c3c2e/delete_my_teams_messages.js#L13

```
Uncaught ReferenceError: jQuery is not defined
```

**Comment by dsci4-hacks** [comment]
Created new version, please test.
